### ISSUE TITLE
How do you use it ?

### ISSUE THREAD

**Issue by grecinto** [FizzerWL/CsScala#1]
I just wanted to try this tool and feed in a set of c# code set(multiple projects/folders & a solution file), see how it will generate Scala code from it.

Thanks for any information.

-Best.

**Comment by FizzerWL** [comment]
CsScala is a console app.  If you build and run it, it will print out usage information:


Usage:
    csscala.exe  /sln:<path to solution file> [options]


Options available:

        /out:<output directory>
                Directory to write scala files to.  If not specified, output will be written to the current working directory.

        /config:<configuration>
                The configuration within the passed solution file to use. (Debug, Release, etc.)

        /projects:<comma-delimited list of project names>
                If you don't want to convert all projects in the passed solution, you can provide a list of project names.  Only the projects named here will be converted.

        /extraTranslation:<path to xml file>
                Defines extra conversion parameters for use with this project.  See Translations.xml for examples.

        /define:<symbol>
                Adds extra pre-processor #define symbols to add to the project before building.
