### ISSUE TITLE
Mode to ignore unsupported c# features

### ISSUE THREAD

**Issue by grecinto** [FizzerWL/CsScala#2]
Is there a mode where unsupported features will just generate a warning or error log/marker but code conversion still proceeds to rest of file?

**Comment by FizzerWL** [comment]
CsScala's design philosophy is that generated code which builds without errors should always run identically to the original.  This is important for transpiling, as it alleviates the need to manually test each piece of generated code -- you're given assurances that, if the code builds, it will run correctly.

I understand that some people use code converters as a way to reduce the manual work involved in porting code.  In other words, they'll use the generated code as a starting point and modify it by hand from there.  In this situation, it makes sense to make a "best guess" and generate code that it can, leaving off code that it doesn't support.  This isn't one of CsScala's goals, so if you want it to do that, you should fork it and add it yourself.
