### ISSUE TITLE
where are the imports found

### ISSUE THREAD

**Issue by srvarey** [FizzerWL/CsScala#9]
These imports are generated in all conversions....

import anonymoustypes._;
import System.CsScala;
import System.CsRef;
import System.CsLock;
import System.CsObject;

Where is the source or jar for these imports?
My scala program won't compile because it can't find them

**Comment by FizzerWL** [comment]
[System](https://github.com/FizzerWL/CsScala/tree/master/System) is right there in the root folder of the source code.

Anonymoustypes is generated by CsScala.exe and put into your project folder if you use any anonymous types (such as `new { One = 1 }`)
